version: '2.3'
#
# Example execution:
# docker-compose run --rm ansibleaws bash
#
services:
  ansibleaws:
    container_name: ansibleaws
    build: ./ansibleaws
    hostname: ansible-29
    mem_limit: 1000m
    volumes:
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
      - type: bind
        source: /etc/group
        target: /etc/group
      - type: bind
        source: ${HOME}/git
        target: /git
      - type: bind
        source: $HOME
        target: $HOME
    environment:
      - "PS1=$$(whoami)@$$(hostname):$$(pwd) $$ "
      - "TsERRAGRUNT_DOWNLOAD=${HOME}/.terragrunt_cache"