---
lightsail_hosts:
  - name: test
    region: eu-central-1
    zone: eu-central-1a
    blueprint_id: amazon_linux_2
    bundle_id: micro_2_0
    user_data: ./inventory/templates/test.j2
    network_filter:
      - fromPort: 22
        toPort: 22
        protocol: tcp
        cidrs:
          - 87.128.0.0/11       # Deutsche Telekom DSL